### ISSUE TITLE
Event type : PUT not working for lower level folders

### ISSUE THREAD

**Issue by varshneyjayant** [cboscolo/elb2loggly#13]
ELB creates logs in defined directory structure with year/month/date in S3, Event type : PUT not working for lower level directories. Changed to ObjectCreated to make it work.

**Comment by varshneyjayant** [comment]
Added update at #14

**Comment by varshneyjayant** [comment]
@cboscolo  please see, I looks an important factor to me.

**Comment by cboscolo** [comment]
Fixed in 3369ee672d809dde517883f221a4da81b2a9ea09
Thanks, @psquickitjayant

**Comment by MarcFletcher** [comment]
I've recently always had my lambda event configured set to the Put source, looks like they changed something recently as this stopped working. Reseting the Lambda event to use "Object Created" as above worked for me.
