### ISSUE TITLE
Improve formatting of elb2loggly.js

### ISSUE THREAD

**Issue by ctrlrsf** [cboscolo/elb2loggly#17]
Formatting/indentation of this file is very inconsistent. Would a PR to clean it up be welcomed? Curious whether spaces or tabs are preferred. If spaces, how many?

**Comment by cboscolo** [comment]
I would welcome this cleanup!  I'm pretty new to Node.js myself, so don't have specific opinions other than being consistent with what a seasoned Node.js developer would expect.  This guide tops google search results: https://github.com/felixge/node-style-guide
