### ISSUE TITLE
InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.

### ISSUE THREAD

**Issue by MarcFletcher** [cboscolo/elb2loggly#3]
Have configured everything as per https://www.loggly.com/docs/aws-elb/ but all lambda events result in a failure, if I attempt to view the cloudtrail logs I get:

![screen shot 2015-07-14 at 20 18 57](https://cloud.githubusercontent.com/assets/3837303/8682564/9dc6467a-2a65-11e5-9ee7-bd32f076d66f.png)

Don't know what to try next as debugging on AWS lambda appears to be rather poor.

**Comment by cesarmc3** [comment]
@Karnifexx Can you share your solution to this case? I'm having the same error. Thanks!

**Comment by MarcFletcher** [comment]
So the invalid access key id came from the fact that the default test s3 put is not a good example. You need to replace all of the JSON entries with valid ones, such as access key etc.

The lack of logs I think was just due to the lambda function never starting due to a permissions error.
