### ISSUE TITLE
Access Denied Error

### ISSUE THREAD

**Issue by MarcFletcher** [cboscolo/elb2loggly#4]
I've just tried setting up this lamda function but am still running into problems. I am using our current ELB logs as a test.

The Lamda function appears to run on every new PUT but the cloudwatch log is showing the following error (I apologise for the screen shot but there does not appear to be a sensible way to COPY/PASTE the logs (i've deleted the bucket name from the screenshot):

![screen shot 2015-07-15 at 13 45 41](https://cloud.githubusercontent.com/assets/3837303/8698772/a7905d1a-2af8-11e5-8be6-00d8fcbb0b3f.png)

Here is my bucket tag config:

![screen shot 2015-07-15 at 13 57 03](https://cloud.githubusercontent.com/assets/3837303/8698900/741946f8-2af9-11e5-8f59-1fd17a41ccac.png)

I have also confirmed that the iam role can access the log files by using the role to access the same file via the S3 API.

**Comment by cboscolo** [comment]
It looks to me like the Lambda does not have access permissions to your S3 bucket.
When you set up the Lambda function did you select "S3 execution role" for it.
Also, when you go to AWS console and look at the Roles in IAM, do you see any called "lambda_s3_exec_role" or similar?  Check the policy that is attached to that role to be sure it allows the Lambda function to access the S3 bucket.

**Comment by MarcFletcher** [comment]
Please see the bottom of my post:

"I have also confirmed that the iam role can access the log files by using the role to access the same file via the S3 API."

Do you believe this is the only probably reason? If so why does the error mention that LOGGLY_URL is not defined?

**Comment by MarcFletcher** [comment]
Screenshots attached:

<img width="1149" alt="screen shot 2015-07-16 at 20 30 35" src="https://cloud.githubusercontent.com/assets/3837303/8733085/9963c64e-2bf9-11e5-8cf4-1df68abaf85a.png">

<img width="866" alt="screen shot 2015-07-16 at 20 31 44" src="https://cloud.githubusercontent.com/assets/3837303/8733099/b798f17a-2bf9-11e5-8320-64e5e06b9a51.png">

**Comment by MarcFletcher** [comment]
I would also be happy to do a screenshare (skype, google hangout) if that might help (email details to marc@echoboxapp.com).

**Comment by kpkristjansson** [comment]
+1
Exactly the same thing happening to me.

**Comment by cboscolo** [comment]
I think I figured out what is going on.  In the IAM console edit the Role Policy for oneClick_lambda_s3_exec_role_XXXXXXXXXX:  
Change:
        "s3:GetObject",
to:
        "s3:Get*",

I think it is failing when trying to read the attribute of the S3 bucket.

**Comment by MarcFletcher** [comment]
I can confirm this is now working for me.

**Comment by kpkristjansson** [comment]
Same here, works now.  Well at least successfully uploading to Loggly but still not seeing my data there yet for some reason.

**Comment by cboscolo** [comment]
Cool.  Sorry that I missed that detail in the original setup info.  I updated it to reflect this change.
